services:
  maani-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Expose the Next.js app on port 3000
    env_file:
      - .env.production  # Load variables from your .env file
    # volumes:
      # - .:/app  # Mount project directory to container
      # - /app/node_modules  # Ensure node_modules is not overwritten
      # - /.next:/app/.next  # Separate volume for .next build files
    networks:
      - prod_network

# volumes:
#   maani-next-build:  # Volume to store .next directory

networks:
  prod_network:
    external: true
