services:
  maani-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Expose the Next.js app on port 3000
    env_file:
      - .env  # Load variables from your .env file
    volumes:
      - .:/app  # Mount project directory to container
      - /app/node_modules # Prevent node_modules from being overwritten
      - maani-next-build:/app/.next  # Separate volume for .next build files
    networks:
      - app-network

volumes:
  maani-next-build:  # Volume to store .next directory

networks:
  app-network:
    driver: bridge
